services:
  inframonitor:
    build: .
    image: inframonitor:latest
    network_mode: host
    restart: unless-stopped

    environment:
      INFRAMONITOR_HOST_ROOT: /host
      INFRAMONITOR_BACKEND_URL: http://127.0.0.1:8000
      INFRAMONITOR_INTERVAL: 60

    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro

  postgres:
    image: postgres:16
    container_name: inframonitor-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: inframonitor
      POSTGRES_USER: inframonitor
      POSTGRES_PASSWORD: inframonitor

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"


volumes:
  postgres_data: