"""Add hosts table and report relationship

Revision ID: 764d7848be6f
Revises: 3d5657b237b8
Create Date: 2026-08-18 10:15:06.235621

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '764d7848be6f'
down_revision: str | Sequence[str] | None = '3d5657b237b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosts_hostname'), 'hosts', ['hostname'], unique=True)
    op.add_column('reports', sa.Column('host_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reports_host_id'), 'reports', ['host_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'hosts', ['host_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_host_id'), table_name='reports')
    op.drop_column('reports', 'host_id')
    op.drop_index(op.f('ix_hosts_hostname'), table_name='hosts')
    op.drop_table('hosts')
    # ### end Alembic commands ###
